language: python
sudo: required
python:
- '2.7'
- '3.5'
install:
- make init
- pip install coveralls==1.1
script: make test
after_success:
- coveralls
- coverage xml
deploy:
  provider: pypi
  user: mailund
  password:
    secure: "K8YRPabk4CXiTJP9P7w0Rz+dnZN2g1cFZwAV8NEKqcOY3sPnkb+mIou7pQE159OtQmCHIxUsgPeFetQ6TyJ+vNOM99vk37rCxhiOXSFqyzdouX6USZ7BHXeetF+SqM8BzNsyILoe/HjIGe4nhk3DJtvrAP+EsPbimnYivS9675S7RNaENbFtNPApRiZbNMOT/olzyJIrhXd4g1x6eBgtSA0EV47T0FIhbeUhYoy18MyLYI0EaTLzhuXFu4VAMSQGuOdukXTXFE+mHbGKhfX5etW855s0wmfOwe4qraty6NOZ0mJqjvzQRqSru1m8uoSguWLG72iOHHZaGbV2pE2DYG8+KWVq16Yaydyz/0U84RdRYZfV+5A9wZVeGhDKPRdTkZQJwUftFsnJgeMSQ6WVYMhFCwcs7Gcv73Eh1ZLqoCDlhvohqdnv89KYPhJuX81jDqRAaOhU1Q+mSXlmAxf9zMaMT5RipCvZEJGl4SRnIKvnGylrxjhCWx2wyTvbCe91YN5LgmtPlwES0L/0UkltB15VKYSAunCDcA97inHvmbCI4aB/tEcByJnHqvF6z8P4d46YV7dWAQeFMCSdIH8f8QpredsBkbuC8g2s3ZRzwnXwnW7TLfoncjagdtbcsuVt9uKWlUwnOZYHefttEv5MZeoUWLbRqcMKn8XOEiIiCHM="
  on:
    tags: true
    branch: master
    distributions: sdist bdist bdist_wheel
after_deploy: bash build_conda.sh
